# Generated by Django 3.2 on 2022-05-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_add_fields_to_film_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personfilmwork',
            name='role',
            field=models.TextField(choices=[('actor', 'actor'), ('producer', 'producer'), ('director', 'director'), ('writer', 'writer')], max_length=255, null=True, verbose_name='role'),
        ),
    ]
