# Generated by Django 4.0.5 on 2022-06-02 10:00

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_personfilmwork_role'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='filmwork',
            index=models.Index(django.db.models.expressions.F('modified'), name='film_work_modified_idx'),
        ),
    ]
